inventory:
  keepExp: false
  respectKeepInv: true
  keepHeld: true
  keepSlots:
    - 0 # Hotbar
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 40 # Off-Hand
    - 36 # Boots
    - 37 # Leggings
    - 38 # Chestplate
    - 39 #
  worldWhitelist:
    - world
    - world_nether
    - world_the_end

skulling:
  initial: 1800
  perHit: 15
  perKill: 600
  removalTime: 1  # every x seconds the value gets decreased. Dont go too low unless NASA
deathban:
  time: 3600
